#!/bin/sh
set -e

# write the php-fpm config
{ \
    echo listen = 127.0.0.1:9000; \
    echo listen.owner = www-data; \
    echo listen.group = www-data; \
    echo listen.mode = 0660; \
    echo listen.backlog = 65535; \
    echo pm.max_children = "$FPM_PM_MAX_CHILDREN"; \
    echo pm.start_servers = "$FPM_PM_START_SERVERS"; \
    echo pm.min_spare_servers = "$FPM_PM_MIN_SPARE_SERVERS"; \
    echo pm.max_spare_servers = "$FPM_PM_MAX_SPARE_SERVERS"; \
    echo access.log = /proc/self/fd/2; \
    echo php_admin_value[error_log] = /proc/self/fd/2; \
    echo php_admin_flag[log_errors] = on;
} > /usr/local/etc/php-fpm.d/zzz-app.conf

exec "$@"
